services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\FormLoginAuthenticator:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $urlGenerator: '@router'
            $logger: '@logger'

    App\Security\GoogleAuthenticator:
        arguments:
            $clientRegistry: '@knpu.oauth2.registry'
            $entityManager: '@doctrine.orm.entity_manager'
            $router: '@router'
            $userRepository: '@App\Repository\UserRepository'
            $passwordHasher: '@security.password_hasher'
            $logger: '@logger'